name: BUILD PIPELINE

on:
  push:
    branches:
      - development

jobs:
  unit-tests:
    uses: ./.github/workflows/unittests.yml
    secrets: inherit

  dependency-review:
    uses: ./.github/workflows/dependency-review.yml
    secrets: inherit
    with:
      base-ref: ${{ github.event.before }}
      head-ref: ${{ github.sha }}

  docker:
    needs: [unit-tests, dependency-review]
    if: needs.unit-tests.result == 'success' && needs.dependency-review.result == 'success'
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    # Needed for docker.yml's OIDC login
    permissions:
      id-token: write
      contents: read
